### ISSUE TITLE
Multivariable Regression

### ISSUE THREAD

**Issue by mh510** [ahensley3/Symbolic-Regression#1]
Thanks for sharing; great package. To get familiar with your code I played around with it and discovered a problem regarding multivariable regression. Here's the data I used as a test bench problem:
```
X = rand(100,2);
y = X(:,1)+X(:,2);
parm.nvars = size(X,2);
config = setup_config(parm);
result = gepfun(X,y,config);
```
I got the error msg: Undefined function or variable 'b'. I solved this problem by adding syms b in line 98 and 129 in the file gepfun.m. Is this a legit fix?

Best regards,
Michael

**Comment by AsherHensley** [comment]
Hi Michael, thanks for catching this! I've updated gepfun.m in the master branch.
